### ISSUE TITLE
有个参数写错了

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [EasternJournalist/live_mocap#6]
body_keypoint_track.py中test函数 引用BodyKeypointTrack
把frame_rate写成了frame_delta

**Comment by EasternJournalist** [comment]
> body_keypoint_track.py中test函数 引用BodyKeypointTrack 把frame_rate写成了frame_delta

谢谢指出！在mocap.py调用的各模块代码中`if __name__ == '__main__': `以下的内容本来是做模块测试的，已经过时，之后我会更新或删除。

**Comment by liuhaorandezhanghao** [comment]
您好，可以发送一份您测试使用的模型吗？我想用你的模型测试下，我的不太对。或者可以添加您的联系方式吗？




---- 回复的原邮件 ----
| 发件人 | Ruicheng ***@***.***> |
| 发送日期 | 2023年03月11日 17:30 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [EasternJournalist/live_mocap] 有个参数写错了 (Issue #6) |

body_keypoint_track.py中test函数 引用BodyKeypointTrack 把frame_rate写成了frame_delta

谢谢指出！在mocap.py调用的各模块代码中if __name__ == '__main__': 以下的内容本来是做模块测试的，已经过时，之后我会更新或删除。
